### ISSUE TITLE
Add an activity which allows user to change language programmatically

### ISSUE THREAD

**Issue by scruel** [VegaBobo/Language-Selector#11]
I can't find anything shell command which can change application locale successfully, so I think we may utilize an existing app to achieve such goal.

FIY, the following commands I've tried won't work:
```
am start <package_name>/<main_activity> --es android.intent.extra.LOCALE en_US
adb shell am broadcast -a com.android.intent.action.SET_LOCALE --es com.android.intent.extra.LOCALE en_US -p <package_name>
```

**Comment by VegaBobo** [comment]
Can you try interacting with locale service using "cmd locale"?

set-app-locales is able to change locales by using:
cmd locale set-app-locales <package name> --locales <locales>

Example, setting "wireguard" app (com.wireguard.android) to pt-BR (Brazilian Portuguese)
cmd locale set-app-locales com.wireguard.android --locales pt-BR

Our app, internally, interact with the same APIs as locale service, so, give it a try!

**Comment by scruel** [comment]
It works! Thanks! How can you know this command?

**Comment by VegaBobo** [comment]
Before creating this app, frustrated because my device doesn't have any UI option to set app languages even on Android 13, so i did some research at AOSP source code, found it, and decided to make this app haha

**Comment by scruel** [comment]
Cool, I did the same thing about checking AOSP source code, though failed to get this command.
